# Generated by Django 4.2.1 on 2023-06-02 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='Movies',
        ),
    ]
