# Generated by Django 4.2.1 on 2023-06-02 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb_app', '0004_movie_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'directors',
            },
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='imdb_app.director'),
        ),
    ]
